image: ubuntu:18.04

build:
  script:
    - apt update
    - apt install -y gnupg wget git unzip tar curl make gcc python3 python3-pip moreutils locales language-pack-en && export LANG=en_US.UTF-8 && export LC_ALL=en_US.UTF-8 && locale-gen en_US.UTF-8
    - useradd -m singularity
    - su -c './entrypoint.sh' singularity