os: linux
dist: bionic
language: c++

before_install:
        - export DEBIAN_FRONTEND=noninteractive

install:
        - sudo apt update && sudo apt install -y gnupg wget git unzip tar curl make gcc python3 python3-pip python3-setuptools moreutils locales language-pack-en && export LANG=en_US.UTF-8 && export LC_ALL=en_US.UTF-8 && sudo locale-gen en_US.UTF-8

script:
        - ./entrypoint.sh
